Document: touchegg-gui
Title: Debian touchegg-gui Manual
Author: <insert document author here>
Abstract: This manual describes what touchegg-gui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/touchegg-gui/touchegg-gui.sgml.gz

Format: postscript
Files: /usr/share/doc/touchegg-gui/touchegg-gui.ps.gz

Format: text
Files: /usr/share/doc/touchegg-gui/touchegg-gui.text.gz

Format: HTML
Index: /usr/share/doc/touchegg-gui/html/index.html
Files: /usr/share/doc/touchegg-gui/html/*.html
