Document: touchegg
Title: Debian touchegg Manual
Author: <insert document author here>
Abstract: This manual describes what touchegg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/touchegg/touchegg.sgml.gz

Format: postscript
Files: /usr/share/doc/touchegg/touchegg.ps.gz

Format: text
Files: /usr/share/doc/touchegg/touchegg.text.gz

Format: HTML
Index: /usr/share/doc/touchegg/html/index.html
Files: /usr/share/doc/touchegg/html/*.html
